services:
  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docdoc

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d docdoc"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8080:8080"

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/docdoc

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
